# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://m.tcio3.top/"
title: Memorial
languageCode: zh
DefaultContentLanguage: zh
theme: [ PaperMod ]

paginate: 9 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°

buildDrafts: false # å‘å¸ƒæ—¶åŒ…å«è‰ç¨¿
buildFuture: false # å‘å¸ƒæ—¶åŒ…å«æœªæ¥æ—¥æœŸçš„å¸–å­
buildExpired: false # å‘å¸ƒæ—¶åŒ…å«å·²è¿‡æœŸçš„å†…å®¹

enableInlineShortcodes: true # å…è®¸å†…è”çŸ­ç 
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
pygmentsUseClasses: true
mainsections: ["post"] # ä¸»é¡µçš„ä¸»è¦åˆ†èŠ‚
# googleAnalytics: UA-123-45 # è°·æ­Œç»Ÿè®¡

minify:
  disableXML: true
  # minifyOutput: true

languages:
  zh:
    languageName: "ä¸­æ–‡"
    weight: 2
    title: ğŸ¨çºªå¿µç¢‘
    taxonomies: # åˆ†ç±»æ³•é…ç½®
      tag: tags
      category: categories
      series: series
      author: author
    menus: # èœå•
      main:
        - name: æ ‡ç­¾
          url: tags
          weight: 10
        - name: åˆ†ç±»
          url: categories
          weight: 20
        - name: ç³»åˆ—
          url: series
          weight: 30
        - name: ä½œè€…
          url: author
          weight: 40
        - name: å¸®åŠ© +
          identifier: help_menu
          url: help_menu
          weight: 50

        - name: ğŸ”æœç´¢
          url: search
          weight: 60
        
        - name: æŒ‡å¯¼
          parent: help_menu
          url: guide
          weight: 10
        - name: å…³äº
          parent: help_menu
          url: about
          weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  footer_author: "TCI Obsv III & ddlcp" # è‡ªå®šä¹‰å‚æ•°ï¼Œç”¨äºåœ¨è„šæ³¨æ˜¾ç¤ºä½œè€…
  description: "Memorial of nothing"
  author: ["åŒ¿åä½œè€…"] # é»˜è®¤ä½œè€…
  # author: ["Me", "You"] # multiple authors
  DateFormat: "06.1.2 PM" # è¿™é‡Œå¿…é¡»å†™æˆ2006å¹´1æœˆ2æ—¥3æ—¶4åˆ†5ç§’ å‘¨ä¸€ ä¸‹åˆ 

  defaultTheme: dark
  disableAnchoredHeadings: false
  # disableThemeToggle: true
  hideSummary: false # éšè—æ¦‚è¦
  ShowShareButtons: true # æ˜¾ç¤ºåˆ†äº«æŒ‰é’®
  ShowWordCount: true # æ˜¾ç¤ºå­—æ•°
  ShowReadingTime: false # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  ShowLastMod: true # æ˜¾ç¤ºä¸Šæ¬¡ä¿®æ”¹
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: false # æ˜¾ç¤ºä¸Šä¸€ä¸ª/ä¸‹ä¸€ä¸ªæŒ‰é’®
  ShowCodeCopyButtons: true # æ˜¾ç¤ºä»£ç å¤åˆ¶æŒ‰é’®
  ShowFullTextinRSS: true # åœ¨rssä¸­æ˜¾ç¤ºå…¨éƒ¨æ–‡æœ¬
  ShowRssButtonInSectionTermList: true # åœ¨æ–‡ä»¶å¤¹é¡µé¢æ˜¾ç¤º Rss æŒ‰é’®
  ShowAllPagesInArchive: false # åœ¨æ—¶é—´çº¿ä¸­æ˜¾ç¤ºæ‰€æœ‰é¡µé¢
  ShowPageNums: true # æ˜¾ç¤ºé¡µç 
  # comments: false
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false

  homeInfoParams: # ä¸»é¡µä¿¡æ¯
    Title: "Memorial"
    Content: >
      It is a memorial in the information age.
      
      - è¿™æ˜¯ä¿¡æ¯æ—¶ä»£çš„ä¸€åº§çºªå¿µç¢‘ã€‚  

      -  

      - Meant to keep the trivial shards.  

      - ç”¨æ¥ä¿ç•™å¾®ä¸è¶³é“çš„ç¢ç‰‡ã€‚  

      -  

      - Before they burn to hell.  

      - åœ¨å®ƒä»¬çƒ§å°½ä¹‹å‰ã€‚

  editPost:
    URL: "../../about/feedback"
    Text: "åé¦ˆ" # edit text
    appendFilePath: false # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  cover:
       hidden: false # hide everywhere but not in structured data
       hiddenInList: false # hide on list pages and home
       hiddenInSingle: true # hide on single page

fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true